spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social_login
    username: springuser
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 238128617745-jq7i2hm18mmrm0l3oviut695nh92enf8.apps.googleusercontent.com
            client-secret: DeeapYdNVf5eas3dKjuoravv
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  secretKey: 034uouoeifjadsofj49i384ui[tqitgj8e99f3q[90tj3p49gj9qe]]
